const datas = [
    {
        id:"1",
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Nike Air Monarch IV",
        price: "2000",
        company: "Nike",
        color: "white",
        category: "sneakers",
    },
    {
        id:"2",
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Adidas Niteball",
        price: "4000",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {
        id:"3",
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Adidas Niteball",
        price: "4000",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {
        id:"4",
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Adidas Niteball",
        price: "4000",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {
        id:"5",
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Adidas Niteball",
        price: "4000",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
]